version: "3.6"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    platform: linux/x86_64
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-volumes:/var/lib/mysql   # 將映射名稱放入映射中
      - ./mysqld.cnf:/etc/musql.conf.d/musqld.cnf
    restart: always
    environment:
      MYSQL_USER: myDb  
      MYSQL_PASSWORD: 123qweASD
      MYSQL_ROOT_PASSWORD: 123qweASD

volumes:
  mysql-data-volumes:
